-- ============================================================
-- ACE IT UP — COMPLETE BACKEND FIX SQL
-- Run this ENTIRE script in Supabase SQL Editor
-- URL: https://supabase.com → Your Project → SQL Editor
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. ADD MISSING COLUMNS TO EXISTING TABLES
-- ─────────────────────────────────────────────────────────────

-- Add score column to gd_sessions (was missing - was using count * 15 hack)
ALTER TABLE public.gd_sessions ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0;

-- Add achievements array to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS achievements JSONB DEFAULT '[]'::jsonb;

-- ─────────────────────────────────────────────────────────────
-- 2. CREATE MISSING TABLES
-- ─────────────────────────────────────────────────────────────

-- user_seen_questions: tracks which questions each user has already seen
CREATE TABLE IF NOT EXISTS public.user_seen_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    question_id BIGINT NOT NULL,
    seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, question_id)
);

ALTER TABLE public.user_seen_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own seen questions" ON public.user_seen_questions;
CREATE POLICY "Users can manage own seen questions"
    ON public.user_seen_questions FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 3. FIX RLS — ENSURE ALL SCORE TABLES ALLOW INSERTS
-- ─────────────────────────────────────────────────────────────

-- Drop and recreate to ensure WITH CHECK clause is included
DROP POLICY IF EXISTS "Users access own aptitude" ON public.aptitude_scores;
CREATE POLICY "Users access own aptitude" ON public.aptitude_scores
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users access own gd" ON public.gd_sessions;
CREATE POLICY "Users access own gd" ON public.gd_sessions
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users access own interview" ON public.interview_scores;
CREATE POLICY "Users access own interview" ON public.interview_scores
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users access own comm" ON public.communication_scores;
CREATE POLICY "Users access own comm" ON public.communication_scores
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users access own logs" ON public.activity_logs;
CREATE POLICY "Users access own logs" ON public.activity_logs
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 4. FIX PROFILES RLS — ALLOW ADMIN READ FOR ADMIN DASHBOARD
-- ─────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;
CREATE POLICY "Admins can view all profiles" ON public.profiles
    FOR SELECT USING (
        auth.uid() = id OR
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

-- ─────────────────────────────────────────────────────────────
-- 5. CREATE XP UPDATE FUNCTION (replaces missing handle_user_activity RPC)
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.update_user_xp(
    p_user_id UUID,
    p_xp_gain INTEGER
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_current_xp INTEGER;
    v_current_level INTEGER;
    v_new_xp INTEGER;
    v_new_level INTEGER;
    v_leveled_up BOOLEAN := false;
    v_current_streak INTEGER;
    v_last_activity DATE;
    v_today DATE := CURRENT_DATE;
    v_new_streak INTEGER;
    v_streak_updated BOOLEAN := false;
BEGIN
    -- Get current profile stats
    SELECT xp, level, streak_count
    INTO v_current_xp, v_current_level, v_current_streak
    FROM public.profiles
    WHERE id = p_user_id;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('leveled_up', false, 'new_level', 1, 'streak_updated', false, 'new_streak', 0);
    END IF;

    -- Calculate new XP
    v_new_xp := v_current_xp + p_xp_gain;

    -- Level up logic: every 500 XP = 1 level
    v_new_level := GREATEST(1, (v_new_xp / 500) + 1);
    IF v_new_level > v_current_level THEN
        v_leveled_up := true;
    END IF;

    -- Streak logic: check last activity log date
    SELECT DATE(created_at) INTO v_last_activity
    FROM public.activity_logs
    WHERE user_id = p_user_id
    ORDER BY created_at DESC
    LIMIT 1;

    IF v_last_activity IS NULL OR v_last_activity < v_today - INTERVAL '1 day' THEN
        -- Streak reset or first activity
        IF v_last_activity = v_today - INTERVAL '1 day' THEN
            v_new_streak := v_current_streak + 1;
        ELSE
            v_new_streak := 1;
        END IF;
        v_streak_updated := true;
    ELSE
        v_new_streak := v_current_streak;
    END IF;

    -- Update profile
    UPDATE public.profiles
    SET
        xp = v_new_xp,
        level = v_new_level,
        streak_count = v_new_streak
    WHERE id = p_user_id;

    RETURN jsonb_build_object(
        'leveled_up', v_leveled_up,
        'new_level', v_new_level,
        'streak_updated', v_streak_updated,
        'new_streak', v_new_streak,
        'total_xp', v_new_xp
    );
END;
$$;

-- Grant execute to authenticated users
GRANT EXECUTE ON FUNCTION public.update_user_xp(UUID, INTEGER) TO authenticated;

-- ─────────────────────────────────────────────────────────────
-- 6. SEED MORE QUESTIONS IF BANK IS SPARSE
-- ─────────────────────────────────────────────────────────────

-- Additional Aptitude Questions (Quants)
INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Quants', 'What is 25% of 480?', '["100","110","120","130"]', '2', 'Beginner', '25/100 × 480 = 120'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'What is 25% of 480?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Quants', 'If a train travels 450 km in 6 hours, what is its speed?', '["65 km/h","70 km/h","75 km/h","80 km/h"]', '2', 'Beginner', '450 ÷ 6 = 75 km/h'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'If a train travels 450 km in 6 hours, what is its speed?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Quants', 'A shopkeeper sells an article at 20% profit. If cost price is ₹500, what is the selling price?', '["₹550","₹580","₹600","₹620"]', '2', 'Intermediate', 'SP = CP × (1 + profit%) = 500 × 1.2 = ₹600'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'A shopkeeper sells an article at 20% profit. If cost price is ₹500, what is the selling price?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Quants', 'The ratio of boys to girls in a class is 3:2. If total students = 40, how many girls?', '["12","14","16","18"]', '2', 'Beginner', 'Girls = (2/5) × 40 = 16'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'The ratio of boys to girls in a class is 3:2. If total students = 40, how many girls?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Quants', 'Simple interest on ₹2000 at 5% for 3 years is:', '["₹200","₹250","₹300","₹350"]', '2', 'Beginner', 'SI = (P × R × T) / 100 = (2000×5×3)/100 = ₹300'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Simple interest on ₹2000 at 5% for 3 years is:');

-- Additional Logical Questions
INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Logical', 'Find the next number: 2, 6, 12, 20, 30, ?', '["40","42","44","46"]', '1', 'Beginner', 'Differences: 4,6,8,10,12 → 30+12=42'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Find the next number: 2, 6, 12, 20, 30, ?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Logical', 'All cats are animals. All animals have four legs. Do all cats have four legs?', '["Yes","No","Cannot determine","Partially"]', '0', 'Beginner', 'Transitive property: Cats → Animals → four legs, so Yes'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'All cats are animals. All animals have four legs. Do all cats have four legs?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Logical', 'A is B''s sister. B is C''s brother. What is A to C?', '["Sister","Brother","Aunt","Cannot determine"]', '0', 'Intermediate', 'A is female (sister of B), so A is sister of C'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'A is B''s sister. B is C''s brother. What is A to C?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Logical', 'What comes next in the series: Z, X, V, T, R, ?', '["P","Q","O","N"]', '0', 'Beginner', 'Skipping one letter backwards: Z-X-V-T-R-P'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'What comes next in the series: Z, X, V, T, R, ?');

-- Additional Verbal Questions
INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Verbal', 'Choose the antonym for "Benevolent":', '["Kind","Generous","Malevolent","Charitable"]', '2', 'Intermediate', 'Malevolent means having or showing a wish to do evil — opposite of benevolent'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Choose the antonym for "Benevolent":');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Verbal', 'Select the correctly spelled word:', '["Accomodate","Accommodate","Acomodate","Acommodate"]', '1', 'Intermediate', 'Accommodate has double c and double m'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Select the correctly spelled word:');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Verbal', 'Choose the synonym for "Ephemeral":', '["Permanent","Transient","Eternal","Solid"]', '1', 'Expert', 'Ephemeral means lasting for a very short time — transient is the best synonym'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Choose the synonym for "Ephemeral":');

-- Interview Questions
INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'interview', 'HR', 'Tell me about yourself and your key strengths.', NULL, NULL, 'Beginner', 'Use STAR method: Structure, mention background, skills, and career goals.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Tell me about yourself and your key strengths.');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'interview', 'HR', 'Describe a situation where you resolved a conflict with a teammate.', NULL, NULL, 'Intermediate', 'Focus on empathy, communication, and positive outcome.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Describe a situation where you resolved a conflict with a teammate.');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'interview', 'Technical', 'Explain the concept of recursion with a real-world example.', NULL, NULL, 'Intermediate', 'Recursion = a function calling itself. Example: factorial, directory traversal.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Explain the concept of recursion with a real-world example.');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'interview', 'HR', 'Where do you see yourself in 5 years?', NULL, NULL, 'Beginner', 'Show ambition aligned with company growth, not just personal gain.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Where do you see yourself in 5 years?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'interview', 'Technical', 'What is the difference between SQL and NoSQL databases?', NULL, NULL, 'Intermediate', 'SQL: structured, relational, ACID. NoSQL: flexible schema, horizontal scaling, eventual consistency.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'What is the difference between SQL and NoSQL databases?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'interview', 'Behavioral', 'Tell me about a time you failed and what you learned from it.', NULL, NULL, 'Intermediate', 'Show growth mindset: acknowledge fault, describe the lesson, explain how you improved.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Tell me about a time you failed and what you learned from it.');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'interview', 'Technical', 'Explain the concept of OOP and its four pillars.', NULL, NULL, 'Expert', 'Encapsulation, Inheritance, Polymorphism, Abstraction — give one real example each.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Explain the concept of OOP and its four pillars.');

-- GD Topics
INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'gd', 'Technology', 'Is Artificial Intelligence a threat or an opportunity for humanity?', NULL, NULL, 'Intermediate', 'Cover both sides: automation vs job creation, ethics, AI alignment'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Is Artificial Intelligence a threat or an opportunity for humanity?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'gd', 'Social', 'Should social media platforms be regulated by the government?', NULL, NULL, 'Intermediate', 'Cover: free speech vs misinformation, privacy, monopoly power'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Should social media platforms be regulated by the government?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'gd', 'Business', 'Work from home vs office — which model is more productive?', NULL, NULL, 'Beginner', 'Cover: productivity metrics, collaboration, mental health, infrastructure'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Work from home vs office — which model is more productive?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'gd', 'Economy', 'Should India focus on manufacturing or services for economic growth?', NULL, NULL, 'Expert', 'GDP contributions, employment, Make in India, IT exports'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Should India focus on manufacturing or services for economic growth?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'gd', 'Education', 'Is online education as effective as traditional classroom education?', NULL, NULL, 'Beginner', 'Access, self-discipline, hands-on learning, socioeconomic divide'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Is online education as effective as traditional classroom education?');

-- Communication Prompts
INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'communication', 'Self Introduction', 'Introduce yourself in 2 minutes as if you are at a job interview.', NULL, NULL, 'Beginner', 'Cover: name, education, experience, skills, career goal'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Introduce yourself in 2 minutes as if you are at a job interview.');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'communication', 'Opinion', 'Speak for 90 seconds on: "Technology has made life easier but lonelier."', NULL, NULL, 'Intermediate', 'Balance both sides clearly with personal examples.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Speak for 90 seconds on: "Technology has made life easier but lonelier."');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'communication', 'Persuasion', 'Convince someone to invest in learning a new skill in just 60 seconds.', NULL, NULL, 'Intermediate', 'Use persuasion techniques: benefits, urgency, social proof'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Convince someone to invest in learning a new skill in just 60 seconds.');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'communication', 'Story Telling', 'Tell a story about a challenge you overcame. Keep it under 2 minutes.', NULL, NULL, 'Beginner', 'Structure: setup → conflict → climax → resolution → lesson'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Tell a story about a challenge you overcame. Keep it under 2 minutes.');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'communication', 'Debate', 'Argue for or against: "Leadership is innate, not taught."', NULL, NULL, 'Expert', 'Pick a side, use examples of great leaders who were self-made.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Argue for or against: "Leadership is innate, not taught."');

-- ─────────────────────────────────────────────────────────────
-- VERIFICATION QUERIES (run these separately to confirm)
-- ─────────────────────────────────────────────────────────────
-- SELECT COUNT(*) FROM public.module_questions;
-- SELECT * FROM public.user_seen_questions LIMIT 5;
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'gd_sessions';
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'profiles';
