-- 1. PROFILES & AUTHENTICATE SETUP
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE,
    full_name TEXT,
    role TEXT DEFAULT 'student' CHECK (role IN ('student', 'admin')),
    level INTEGER DEFAULT 1,
    xp INTEGER DEFAULT 0,
    streak_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Idempotent Policies for Profiles
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;

CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- 2. MODULE SYSTEM
CREATE TABLE IF NOT EXISTS public.module_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_type TEXT NOT NULL CHECK (module_type IN ('aptitude', 'gd', 'interview', 'communication')),
    category TEXT NOT NULL,
    question_text TEXT NOT NULL,
    options JSONB,
    correct_answer TEXT,
    difficulty TEXT DEFAULT 'Beginner' CHECK (difficulty IN ('Beginner', 'Intermediate', 'Expert')),
    explanation TEXT,
    keywords TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.module_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view questions" ON public.module_questions;
DROP POLICY IF EXISTS "Admins can modify questions" ON public.module_questions;

CREATE POLICY "Anyone can view questions" ON public.module_questions FOR SELECT USING (true);
CREATE POLICY "Admins can modify questions" ON public.module_questions FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 3. SCORE TRACKING
CREATE TABLE IF NOT EXISTS public.aptitude_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    topic TEXT,
    score INTEGER,
    total_questions INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.gd_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    topic TEXT,
    duration_seconds INTEGER,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.interview_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    question_category TEXT,
    evaluation_score INTEGER,
    feedback TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.communication_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    prompt TEXT,
    fluency_rating INTEGER,
    clarity_rating INTEGER,
    confidence_rating INTEGER,
    overall_score INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.aptitude_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gd_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.communication_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own aptitude" ON public.aptitude_scores;
DROP POLICY IF EXISTS "Users access own gd" ON public.gd_sessions;
DROP POLICY IF EXISTS "Users access own interview" ON public.interview_scores;
DROP POLICY IF EXISTS "Users access own comm" ON public.communication_scores;

CREATE POLICY "Users access own aptitude" ON public.aptitude_scores FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users access own gd" ON public.gd_sessions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users access own interview" ON public.interview_scores FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users access own comm" ON public.communication_scores FOR ALL USING (auth.uid() = user_id);

-- 4. ROADMAPS & TASKS
CREATE TABLE IF NOT EXISTS public.roadmaps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    title TEXT DEFAULT 'Elite Placement Track',
    current_week INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.daily_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT REFERENCES public.roadmaps(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.roadmaps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_tasks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own roadmap" ON public.roadmaps;
DROP POLICY IF EXISTS "Users access own tasks" ON public.daily_tasks;

CREATE POLICY "Users access own roadmap" ON public.roadmaps FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users access own tasks" ON public.daily_tasks FOR ALL USING (
    EXISTS (SELECT 1 FROM public.roadmaps WHERE id = daily_tasks.roadmap_id AND user_id = auth.uid())
);

-- 5. RESUMES
CREATE TABLE IF NOT EXISTS public.resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    content JSONB NOT NULL,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.resumes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own resumes" ON public.resumes;

CREATE POLICY "Users access own resumes" ON public.resumes FOR ALL USING (auth.uid() = user_id);

-- 6. ACTIVITY LOGS
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    action_type TEXT NOT NULL,
    context TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own logs" ON public.activity_logs;

CREATE POLICY "Users access own logs" ON public.activity_logs FOR ALL USING (auth.uid() = user_id);

-- 7. GLOBAL LEADERBOARD VIEW
DROP VIEW IF EXISTS public.global_leaderboard;
CREATE OR REPLACE VIEW public.global_leaderboard AS
SELECT 
    p.id,
    p.full_name,
    p.level,
    p.xp,
    p.streak_count,
    ROW_NUMBER() OVER (ORDER BY p.xp DESC) as rank
FROM public.profiles p;

-- 8. INITIAL SEED DATA
INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Quants', 'What is the value of 15% of 200?', '["20", "30", "40", "50"]', '1', 'Beginner', '15/100 * 200 = 30'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'What is the value of 15% of 200?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Quants', 'A car travels 300km in 5 hours. What is its speed?', '["50km/h", "60km/h", "70km/h", "80km/h"]', '1', 'Beginner', '300 / 5 = 60'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'A car travels 300km in 5 hours. What is its speed?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Logical', 'If all Bloops are Razzies and all Razzies are Lurgies, are all Bloops definitely Lurgies?', '["Yes", "No", "Maybe", "Insufficient Info"]', '0', 'Beginner', 'A implies B, B implies C => A implies C'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'If all Bloops are Razzies and all Razzies are Lurgies, are all Bloops definitely Lurgies?');

INSERT INTO public.module_questions (module_type, category, question_text, options, correct_answer, difficulty, explanation)
SELECT 'aptitude', 'Verbal', 'Choose the synonym for "Abundant":', '["Scarce", "Plentiful", "Rare", "Limited"]', '1', 'Beginner', 'Abundant means existing in large quantities.'
WHERE NOT EXISTS (SELECT 1 FROM public.module_questions WHERE question_text = 'Choose the synonym for "Abundant":');
