-- PLATFORM RESOURCES & SOCIAL INTEGRATION
CREATE TABLE IF NOT EXISTS public.platform_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    type TEXT CHECK (type IN ('youtube', 'instagram', 'linkedin', 'twitter', 'website')),
    category TEXT DEFAULT 'General',
    thumbnail_url TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.platform_resources ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view resources" ON public.platform_resources;
CREATE POLICY "Anyone can view resources" ON public.platform_resources FOR SELECT USING (true);

-- SEED DATA: Expert Masterclasses
INSERT INTO public.platform_resources (title, url, type, category, description, thumbnail_url)
VALUES 
('Mastering the STAR Method', 'https://www.youtube.com/watch?v=0nN6aV-UInM', 'youtube', 'Interview', 'How to structure your behavioral interview answers for maximum impact.', 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&q=80'),
('Quantitative Aptitude Shortcuts', 'https://www.youtube.com/watch?v=R96R8L_m284', 'youtube', 'Aptitude', 'Speed math techniques for competitive placement exams.', 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80'),
('Group Discussion Body Language', 'https://www.youtube.com/watch?v=68m_X78N6_M', 'youtube', 'GD', 'Non-verbal cues that differentiate leaders in a group discussion.', 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80'),
('Professional Email Etiquette', 'https://www.youtube.com/watch?v=2fInN_E24XY', 'youtube', 'Communication', 'How to write emails that recruiters actually want to read.', 'https://images.unsplash.com/photo-1557200134-90327ee9fafa?w=800&q=80');

-- SEED DATA: Social Links
INSERT INTO public.platform_resources (title, url, type, category)
VALUES 
('Ace It Up LinkedIn', 'https://linkedin.com/company/aceitup', 'linkedin', 'Social'),
('Ace It Up Instagram', 'https://instagram.com/aceitup', 'instagram', 'Social'),
('Ace It Up X', 'https://twitter.com/aceitup', 'twitter', 'Social');
